### PR TITLE
jupyter_kernel_gateway 3.0.0 (with tests)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- includes #22
- blocked by https://github.com/conda-forge/tornado-feedstock/pull/62

Changes:
- [x] update deps (basically from `grayskull`)
- [x] update recipe metadata and variable usage
- [x] sort deps 
- [x] update `pip` invocation
- [x] add tests with coverage (one skip for a flaky test) 
- [x] add `grayskull` hints for future PRs 
- [x] add maintainer :wave:

### CODE REVIEW

**Comment by bollwyvl** [comment]
Will rekick if the tornado upstream goes through...

**Review by kevin-bates — APPROVED** [review]
Thank you @bollwyvl!

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/jupyter_kernel_gateway ready for review

**Review by kevin-bates — APPROVED** [review]
LGTM, thank you!

**Comment by bollwyvl** [comment]
@conda-forge/jupyter_kernel_gateway thoughts?

**Pull request merged**
