### PR TITLE
REL: 2.0.1

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by isuruf** [comment]
Do you want to try [`noarch: python`](https://github.com/conda-forge/conda-forge.github.io/blob/master/src/meta.rst#building-noarch-packages)?

**Comment by parente** [comment]
Sure. Here goes ...

**Comment by parente** [comment]
Looks like it built without error. Merging!

**Comment by parente** [comment]
Looks like CI systems failed on merge though.

* https://travis-ci.org/conda-forge/jupyter_kernel_gateway-feedstock/builds/274679368
* https://circleci.com/gh/conda-forge/jupyter_kernel_gateway-feedstock/20

/cc @ocefpaf

**Comment by ocefpaf** [comment]
The build worked, only the upload failed :-/

Maybe the token was not properly updated here... I'll check tomorrow morning if no one beats me to it.

**Comment by parente** [comment]
@ocefpaf To update the token, do I just hit it with conda-smithy?

**Comment by isuruf** [comment]
You need to rerender after adding `noarch: python`

**Pull request merged**
