### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.0

### PR DESCRIPTION
**Pull request by parente**
To switch to noarch.

### CODE REVIEW

**Comment by parente** [comment]
@isuruf @ocefpaf This PR built fine on circle, but I got an email after merging it that the upload failed as well.  Is there something else I missed besides re-rendering?

**Comment by isuruf** [comment]
It's uploaded from the previous merge. There's nothing you have to do. The failure is because upload code is trying to figure out whether the distribution is uploaded or not and gets it incorrect and tried to upload again which leads to the failure.

**Comment by parente** [comment]
Ah. Got it. Sorry for the noise and thanks for the help.

**Comment by jakirkham** [comment]
> The failure is because upload code is trying to figure out whether the distribution is uploaded or not and gets it incorrect and tried to upload again which leads to the failure.

That's interesting. Has this been occurring a lot? Does it just happen with noarch packages?

**Pull request merged**
